name: build
on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
env:
  TARGET: onbroid-go

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux, windows]
      fail-fast: false
    env:
      ASSET_NAME: onbroid-go-${{ matrix.goos }}-amd64
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - run: mkdir bin
    - name: build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: amd64
      run: go build -o bin/
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ASSET_NAME }}
        path: bin
    - name: discord notify
      if: always()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        job: ${{ env.TARGET }} - ${{ matrix.goos }}
        